try {
    console.log('Try Block Started!');
    lalala;
    console.log('Try Block Ended!');
}catch(err) {
    // console.log(err);
    console.log('From Catch Block');
}